### ISSUE TITLE
Кросспроверка-дз-2

### ISSUE THREAD

**Issue by VARWA** [leshgun/simplify_the_task#5]
Поставил ***24 балла***.
-2 балла за Интернационализацию (на апк и на эмуляторе не работает)

При flutter analyze выдает следующие предупреждения:

- `   info - The variable name '_$$_TaskModelFromJson' isn't a lowerCamelCase identifier - lib\models\task_model.g.dart:9:14 - non_constant_identifier_names`

- `   info - The variable name '_$$_TaskModelToJson' isn't a lowerCamelCase identifier - lib\models\task_model.g.dart:19:22 - non_constant_identifier_names`

За них баллы не снимал

**Comment by leshhub** [comment]
> Поставил _**24 балла**_. -2 балла за Интернационализацию (на апк и на эмуляторе не работает)
> 
> При flutter analyze выдает следующие предупреждения:
> 
> * `   info - The variable name '_$$_TaskModelFromJson' isn't a lowerCamelCase identifier - lib\models\task_model.g.dart:9:14 - non_constant_identifier_names`
> * `   info - The variable name '_$$_TaskModelToJson' isn't a lowerCamelCase identifier - lib\models\task_model.g.dart:19:22 - non_constant_identifier_names`
> 
> За них баллы не снимал

Локализация (не путать с интернационализацией) не работает из-за того, что я забыл раскомментировать строчку после отладки:
https://github.com/leshgun/simplify_the_task/blob/59c2b9fa3d55778532f0f3b061f232d6c599b113/lib/main.dart#L31-L34
Но даже так, этот пункт выполняется, так как для интернационализации нет необходимости добавлять новые языки, а нужно просто дать возможность быстро добавить локализацию (не хардкодить слова определённого языка). Об этом говорилось ещё в [первой лекции](https://youtu.be/vrSAHrU5NQ4?t=3105).

По поводу анализатора, то эти файлы были автоматически сгенерированы пакетом "freezed". Почему они использовали такой синтаксис - одному богу известно.
